### ISSUE TITLE
OnDragOverEnter is not fired for disabled or non-items in list.

### ISSUE THREAD

**Issue by yuvii** [voidberg/html5sortable#44]
excluded options can create a block at the end or start of the list. It's a weird behavior - one would expect to be able to drag enabled options to the end of the list even if there's a disabled option there. It gets weirder if you have an enabled option last, and you drag it to the center - then you can't take it back: [**demo**](http://jsfiddle.net/yuvii/q1nerbno/)

I tried fixing this by setting up a variable named `allitems` that includes all the children (including excluded ones) and applying the `dragover`, `dragenter` and `drop` events to those. The results were weird - enabled options that allow dragging through disabled options, but if placed become nested within it: [**demo**](http://jsfiddle.net/yuvii/w5Lf29zh/). 

Is there any good solution to this?

**Comment by yuvii** [comment]
And... ok, solved I think. I just used `allitems` in line 127:  `if (allitems.is(this)) {`: [**DEMO**](http://jsfiddle.net/yuvii/w5Lf29zh/2/).

If other people are interested, I'll do a pull request

**Comment by lukasoppermann** [comment]
The issue still persists: When dragging an item onto a disabled item or onto something in the list that is not an item, e.g. a header like `<lh>` the `OnDragOverEnter` event is not fired as it currently only fires for items.

This means you can not move an item between two disabled items. This can be tested on the docs page in the "Exclude items & nested list" example.

As suggested by @yuvii this is solvable by adding this event to any item in the list, instead of only the filtered items that conform the the selector from the options.
